name: Notify Discord on Issue Creation

on:
  issues:
    types: [opened]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Webhook
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          ISSUE_TITLE="${{ github.event.issue.title }}"
          ISSUE_BODY="${{ github.event.issue.body }}"
          ISSUE_URL="${{ github.event.issue.html_url }}"
          ISSUE_USER="${{ github.event.issue.user.login }}"
          PAYLOAD=$(jq -n \
            --arg title "[growly-group/docs-devscout] $ISSUE_TITLE" \
            --arg url "$ISSUE_URL" \
            --arg body "$ISSUE_BODY" \
            --arg user "$ISSUE_USER" \
            '{
              "embeds": [
                {
                  "title": $title,
                  "url": $url,
                  "description": $body,
                  "color": 5814783,
                  "author": {
                    "name": $user
                  }
                }
              ]
            }')
          curl -H "Content-Type: application/json" -X POST -d "$PAYLOAD" "$DISCORD_WEBHOOK"